### ISSUE TITLE
Add ports for switches 

### ISSUE THREAD

**Issue by ChrisAmaya** [USST-RADSAT-SK/power-and-electrical#5]
DF13-2P-125H

**Comment by rileyrox-arn725** [comment]
DF13-2P-125H: This is a surface mount right angle header and not molex microfit as outlined by the design document for the timerboard currently on the dropbox

These are 2 and 4 pin throughole microfit3.0 Molex connectors that already have a footprint in the kicad libraries
Both are available on digikey sold individually for 0.87 and 1.49 CAD respectively
0436500215: 2 pin
0436500415: 4 pin

**Comment by ChrisAmaya** [comment]
For the connectors by the battery, it might be a good idea to use vertical (inhibits, RBF) because the battery board is above the timerboard

rest of connectors are whatever makes sense

MicroUSB should not be vertical

**Comment by ChrisAmaya** [comment]
MicroUSB should be on the left side of the board (pins top of the view)
(-y on the Solidworks model)

**Comment by ChrisAmaya** [comment]
15.2 mm of clearance between timerboard and battery

**Comment by ChrisAmaya** [comment]
![image](https://user-images.githubusercontent.com/57199072/120409605-83047d00-c30e-11eb-959d-ba587bfe1148.png)

**Comment by ChrisAmaya** [comment]
![Uploading image.png…]()

**Comment by ChrisAmaya** [comment]
![Uploading image.png…]()

**Comment by rileyrox-arn725** [comment]
Through-hole header vertical mount 2,3,4 pins
DF13-2P-1.25DSA
DF13-3P-1.25DSA
DF13-4P-1.25DSA

**Comment by rileyrox-arn725** [comment]
corresponding connectors 
DF13-2S-1.25C
DF13-3S-1.25C
DF13-4S-1.25C
